{% set version = "0.3.9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-raceid
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RaceID_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RaceID/RaceID_{{ version }}.tar.gz
  sha256: 41d368e20c4276d1ce206a471d50074d9bc67f4162f9d798a4d0f6aa245f8701

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cluster
    - r-coop
    - r-fateid
    - r-fnn
    - r-fpc
    - r-ggplot2
    - r-harmony
    - r-ica
    - r-igraph
    - r-irlba
    - r-leiden
    - r-locfit
    - r-mass
    - r-matrix
    - r-matrixstats
    - r-pheatmap
    - r-princurve
    - r-quadprog
    - r-randomforest
    - r-rcolorbrewer
    - r-rcpp
    - r-rtsne
    - r-runner
    - r-umap
    - r-vegan
  run:
    - r-base
    - r-cluster
    - r-coop
    - r-fateid
    - r-fnn
    - r-fpc
    - r-ggplot2
    - r-harmony
    - r-ica
    - r-igraph
    - r-irlba
    - r-leiden
    - r-locfit
    - r-mass
    - r-matrix
    - r-matrixstats
    - r-pheatmap
    - r-princurve
    - r-quadprog
    - r-randomforest
    - r-rcolorbrewer
    - r-rcpp
    - r-rtsne
    - r-runner
    - r-umap
    - r-vegan

test:
  commands:
    - $R -e "library('RaceID')"           # [not win]
    - "\"%R%\" -e \"library('RaceID')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RaceID
  license: GPL-3.0-only
  summary: Application of 'RaceID' allows inference of cell types and prediction of lineage trees by he StemID2 algorithm. Herman, J.S., Sagar, Grün D. (2018) <DOI:10.1038/nmeth.4662>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
