bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: Bpoq42zA7pw9eOQ6uMOHiJbzR4i/TGd5XHalxs0rvQKa/ueKuICUVWCq41jjXtF/CwuJ87+eaUY4Mu48n9q9Kny6eOsPnpbAOoniwwN3jDVKcXiaAUlHv3wW4ePoVdeZLA5a3gd18DyT7t2qKqzP3Sbb2vVbaykG7Pn3vVUoLIFR+qs0MyLhVjnhIvPn9zvLZWEQKT5Su3PGnw/bPMiCPf2cgVacyXzWPMiN9M0zXq1hBmbK5CfNnn87DJCn+VXgabhdl7CQj4y273uvNh9SqxMusFIOdh29rANNxX5kc4t0FF9t/VWOC6nWdIZjFLwfHR6v7Wne27zptqzHq5YySuFvY+SrMRHIbntMLB08Xh4QA8UbjZCwYqjFLfCN7MeK0klccItSVp+7ej6F52Wzc0phH3L8/G/cc6Ffuor7KYrnb+vDXv9o7c5wEiQ+EUkgnKDF26RaSoNzFIMIHca7mV2vB3XyZyJlDMS8dFWNBebyids4lgV6s1j6qJifvaT8ZPp0HMO8x6MncnR+JVneNGw/Ugj4iBwh0WsGjSakLiNdbIQU0CorZWkZFCz8rTVFDAK2aAUFo1wN2gDV90EjtmfdNlyM4btSkcPXqWDojTQgq891nkg5t0FwXnzmTe4osbxjeh2+DV254owT5uzPqVGFo2JdI5YMmgjX7tab8oM=
conda_forge_output_validation: true
